version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user-name
      POSTGRES_PASSWORD: strong-password
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "8055:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex-router.entrypoints=web
      - traefik.http.routers.plex-router.rule=Host('<your_domain>.com')
      - traefik.http.services.plex-service.loadbalancer.server.port=80
volumes:
  local_pgdata:
  pgadmin-data:
networks:
  default:
    external: true
    name: traefik_network  # Assuming your Traefik network is named "traefik_network"
