version: '3.7'

services:
  traefik:
    image: traefik:v2.10   # Use the appropriate version
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
